//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `HelloWorldCallback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Deploy;

public interface HelloWorldCallbackSenderPrx extends com.zeroc.Ice.ObjectPrx
{
    default String printFibonacci(String hostname, String input)
    {
        return printFibonacci(hostname, input, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String printFibonacci(String hostname, String input, java.util.Map<String, String> context)
    {
        return _iceI_printFibonacciAsync(hostname, input, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> printFibonacciAsync(String hostname, String input)
    {
        return _iceI_printFibonacciAsync(hostname, input, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> printFibonacciAsync(String hostname, String input, java.util.Map<String, String> context)
    {
        return _iceI_printFibonacciAsync(hostname, input, context, false);
    }

    /**
     * @hidden
     * @param iceP_hostname -
     * @param iceP_input -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_printFibonacciAsync(String iceP_hostname, String iceP_input, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "printFibonacci", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_hostname);
                     ostr.writeString(iceP_input);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String registerClient(HelloWorldCallbackReceiverPrx proxy, String hostname)
    {
        return registerClient(proxy, hostname, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String registerClient(HelloWorldCallbackReceiverPrx proxy, String hostname, java.util.Map<String, String> context)
    {
        return _iceI_registerClientAsync(proxy, hostname, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> registerClientAsync(HelloWorldCallbackReceiverPrx proxy, String hostname)
    {
        return _iceI_registerClientAsync(proxy, hostname, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> registerClientAsync(HelloWorldCallbackReceiverPrx proxy, String hostname, java.util.Map<String, String> context)
    {
        return _iceI_registerClientAsync(proxy, hostname, context, false);
    }

    /**
     * @hidden
     * @param iceP_proxy -
     * @param iceP_hostname -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_registerClientAsync(HelloWorldCallbackReceiverPrx iceP_proxy, String iceP_hostname, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerClient", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeProxy(iceP_proxy);
                     ostr.writeString(iceP_hostname);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String sendMessage(String hostname, String input)
    {
        return sendMessage(hostname, input, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String sendMessage(String hostname, String input, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(hostname, input, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> sendMessageAsync(String hostname, String input)
    {
        return _iceI_sendMessageAsync(hostname, input, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> sendMessageAsync(String hostname, String input, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(hostname, input, context, false);
    }

    /**
     * @hidden
     * @param iceP_hostname -
     * @param iceP_input -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_sendMessageAsync(String iceP_hostname, String iceP_input, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_hostname);
                     ostr.writeString(iceP_input);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void sendBroadcast(String hostname, String input)
    {
        sendBroadcast(hostname, input, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendBroadcast(String hostname, String input, java.util.Map<String, String> context)
    {
        _iceI_sendBroadcastAsync(hostname, input, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendBroadcastAsync(String hostname, String input)
    {
        return _iceI_sendBroadcastAsync(hostname, input, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendBroadcastAsync(String hostname, String input, java.util.Map<String, String> context)
    {
        return _iceI_sendBroadcastAsync(hostname, input, context, false);
    }

    /**
     * @hidden
     * @param iceP_hostname -
     * @param iceP_input -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendBroadcastAsync(String iceP_hostname, String iceP_input, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendBroadcast", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_hostname);
                     ostr.writeString(iceP_input);
                 }, null);
        return f;
    }

    default String listClients()
    {
        return listClients(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String listClients(java.util.Map<String, String> context)
    {
        return _iceI_listClientsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> listClientsAsync()
    {
        return _iceI_listClientsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> listClientsAsync(java.util.Map<String, String> context)
    {
        return _iceI_listClientsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_listClientsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listClients", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static HelloWorldCallbackSenderPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), HelloWorldCallbackSenderPrx.class, _HelloWorldCallbackSenderPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static HelloWorldCallbackSenderPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), HelloWorldCallbackSenderPrx.class, _HelloWorldCallbackSenderPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static HelloWorldCallbackSenderPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), HelloWorldCallbackSenderPrx.class, _HelloWorldCallbackSenderPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static HelloWorldCallbackSenderPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), HelloWorldCallbackSenderPrx.class, _HelloWorldCallbackSenderPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static HelloWorldCallbackSenderPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, HelloWorldCallbackSenderPrx.class, _HelloWorldCallbackSenderPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static HelloWorldCallbackSenderPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, HelloWorldCallbackSenderPrx.class, _HelloWorldCallbackSenderPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (HelloWorldCallbackSenderPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_adapterId(String newAdapterId)
    {
        return (HelloWorldCallbackSenderPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (HelloWorldCallbackSenderPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (HelloWorldCallbackSenderPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_invocationTimeout(int newTimeout)
    {
        return (HelloWorldCallbackSenderPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_connectionCached(boolean newCache)
    {
        return (HelloWorldCallbackSenderPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (HelloWorldCallbackSenderPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_secure(boolean b)
    {
        return (HelloWorldCallbackSenderPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (HelloWorldCallbackSenderPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_preferSecure(boolean b)
    {
        return (HelloWorldCallbackSenderPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (HelloWorldCallbackSenderPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (HelloWorldCallbackSenderPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_collocationOptimized(boolean b)
    {
        return (HelloWorldCallbackSenderPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_twoway()
    {
        return (HelloWorldCallbackSenderPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_oneway()
    {
        return (HelloWorldCallbackSenderPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_batchOneway()
    {
        return (HelloWorldCallbackSenderPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_datagram()
    {
        return (HelloWorldCallbackSenderPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_batchDatagram()
    {
        return (HelloWorldCallbackSenderPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_compress(boolean co)
    {
        return (HelloWorldCallbackSenderPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_timeout(int t)
    {
        return (HelloWorldCallbackSenderPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_connectionId(String connectionId)
    {
        return (HelloWorldCallbackSenderPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default HelloWorldCallbackSenderPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (HelloWorldCallbackSenderPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Deploy::HelloWorldCallbackSender";
    }
}
